"""empty message

Revision ID: 524cdd68d288
Revises: 
Create Date: 2020-07-02 20:28:39.768128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524cdd68d288'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_data',
    sa.Column('dbid', sa.INTEGER(), nullable=False),
    sa.Column('DBDSMID', sa.String(length=100), nullable=True),
    sa.Column('Disease', sa.String(length=100), nullable=True),
    sa.Column('DOID', sa.String(length=100), nullable=True),
    sa.Column('Gene', sa.String(length=100), nullable=True),
    sa.Column('GeneID', sa.String(length=100), nullable=True),
    sa.Column('MIM', sa.String(length=100), nullable=True),
    sa.Column('Map_Location', sa.String(length=100), nullable=True),
    sa.Column('VariantType', sa.String(length=100), nullable=True),
    sa.Column('Protein', sa.String(length=100), nullable=True),
    sa.Column('cDNA', sa.String(length=100), nullable=True),
    sa.Column('SNPID', sa.String(length=100), nullable=True),
    sa.Column('CodonChange', sa.String(length=100), nullable=True),
    sa.Column('RefseqTranscript', sa.String(length=255), nullable=True),
    sa.Column('P_Value', sa.String(length=100), nullable=True),
    sa.Column('Strand', sa.String(length=100), nullable=True),
    sa.Column('GRCh38_Position', sa.String(length=100), nullable=True),
    sa.Column('GRCh37_Position', sa.String(length=100), nullable=True),
    sa.Column('Ref', sa.String(length=100), nullable=True),
    sa.Column('Alt', sa.String(length=100), nullable=True),
    sa.Column('Year', sa.String(length=100), nullable=True),
    sa.Column('PMID', sa.String(length=100), nullable=True),
    sa.Column('Ethnicity', sa.String(length=100), nullable=True),
    sa.Column('Classification', sa.String(length=100), nullable=True),
    sa.Column('StrengthOfEvidence', sa.String(length=255), nullable=True),
    sa.Column('KeySentence', sa.String(length=255), nullable=True),
    sa.Column('PhyloP100way', sa.String(length=100), nullable=True),
    sa.Column('PhastCons100way', sa.String(length=100), nullable=True),
    sa.Column('GerpS', sa.String(length=100), nullable=True),
    sa.Column('Silva', sa.String(length=100), nullable=True),
    sa.Column('DDIG', sa.String(length=100), nullable=True),
    sa.Column('FATHMM_MKL', sa.String(length=100), nullable=True),
    sa.Column('CADD', sa.String(length=100), nullable=True),
    sa.Column('Trap', sa.String(length=100), nullable=True),
    sa.Column('DBDSMScore', sa.String(length=100), nullable=True),
    sa.Column('Source', sa.String(length=100), nullable=True),
    sa.Column('Chromosome', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('dbid')
    )
    op.create_table('tbsubmit',
    sa.Column('tbid', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('joumal', sa.String(length=200), nullable=True),
    sa.Column('gene', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('mutation', sa.String(length=200), nullable=True),
    sa.Column('more', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('tbid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbsubmit')
    op.drop_table('all_data')
    # ### end Alembic commands ###
